[supervisord]
nodaemon=true

[program:ports_snapshot]
command=/opt/venv/bin/python /opt/ufm/ufm_plugin_ports_snapshot/ports_snapshot_plugin/src/app.py
autostart=true
autorestart=true
stdout_logfile=/log/ports_snapshot.log
stderr_logfile=/log/ports_snapshot.err
environment=PYTHONUNBUFFERED="1"
