{
 "title": "UFM monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Server CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "server_cpu_usage_percent_avg{duration=~\"Last 5 minutes\"}",
     "legendFormat": "average server cpu usage"
    },
    {
     "expr": "server_cpu_usage_percent_max{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "max server cpu  usage"
    },
    {
     "expr": "server_cpu_usage_percent_min{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "min server cpu usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "server_memory_usage_percent_avg{duration=~\"Last 5 minutes\"}",
     "legendFormat": "average server memory usage"
    },
    {
     "expr": "server_memory_usage_percent_max{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "max server memory usage"
    },
    {
     "expr": "server_memory_usage_percent_min{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "min server memory usage"
    }
   ]
  },
  {
   "title": "UFM Model Main IO Byte rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "io_bytes_read{duration=~\"Last 5 minutes\"}",
     "legendFormat": "ufm model main io_bytes_read "
    },
    {
     "expr": "io_bytes_write{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "ufm model main io_bytes_write"
    }
   ]
  },
  {
   "title": "UFM Model Main CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ufm_model_main_cpu_usage_percent_avg{duration=~\"Last 5 minutes\"}",
     "legendFormat": "average ufm model main cpu usage"
    },
    {
     "expr": "ufm_model_main_cpu_usage_percent_max{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "max  ufm model main cpu  usage"
    },
    {
     "expr": "ufm_model_main_cpu_usage_percent_min{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "min  ufm model main cpu usage"
    }
   ]
  },
  {
   "title": "UFM Model Main Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ufm_model_main_memory_usage_percent_avg{duration=~\"Last 5 minutes\"}",
     "legendFormat": "average ufm model main memory usage"
    },
    {
     "expr": "ufm_model_main_memory_usage_percent_max{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "max  ufm model main memory usage"
    },
    {
     "expr": "ufm_model_main_memory_usage_percent_min{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "min  ufm model main memory usage"
    }
   ]
  },
  {
   "title": "UFM Model Main IO Packet rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "operations/sec" } },
   "targets": [
    {
     "expr": "io_count_read{duration=~\"Last 5 minutes\"}",
     "legendFormat": "ufm model main io_count_read "
    },
    {
     "expr": "io_count_write{duration=~\"Last 5 minutes\"}\r\n",
     "legendFormat": "ufm model main io_count_write"
    }
   ]
  },
  {
   "title": "UFM  Telemetry stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "telemetry_stat_handled_devices_num{}",
     "legendFormat": "total  handled telemetry devices"
    },
    {
     "expr": "telemetry_stat_handled_ports_num{}",
     "legendFormat": "total handled telemetry ports"
    }
   ]
  },
  {
   "title": "UFM  Telemetry stat rates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ports/sec" } },
   "targets": [
    {
     "expr": "telemetry_stat_handled_devices_rate{}",
     "legendFormat": " handled telemetry devices rate"
    },
    {
     "expr": "telemetry_stat_handled_ports_rate{}",
     "legendFormat": "handled telemetry ports rate"
    }
   ]
  },
  {
   "title": "UFM  Telemetry Stats Handled Total Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "telemetry_stat_handled_total_time {}",
     "legendFormat": "total time to handle telemetry msg "
    }
   ]
  },
  {
   "title": "Prometheus Status ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Devices and Ports Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "events_history_counter{duration=\"Last 5 minutes\"}",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Event Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "events/sec" } },
   "targets": [
    { "expr": "events_rate{}", "legendFormat": "events_rate " }
   ]
  },
  {
   "title": "Average response time  per API",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rest_api_response_time_average{}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Max response time  per API",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rest_api_response_time_max{}", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}