{
 "title": "UFM Events",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Events Stats By Severity",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (count_over_time({job=\"ufm-events\"}[$__range]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Events Stats By Category",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (count_over_time({job=\"ufm-events\"}[$__range]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Recent Significant Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"ufm-events\", severity=~\"CRITICAL|MINOR|WARNING\"} | json"
    }
   ]
  },
  {
   "title": "Link Down Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"ufm-events\"} \r\n|= `Link went down` \r\n| json"
    }
   ]
  }
 ]
}