{
 "title": "UFM Events",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Events Stats By Severity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (count_over_time({job=\"ufm-events\"}[$__range]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Events Stats By Category",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (count_over_time({job=\"ufm-events\"}[$__range]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Last 1000 Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"ufm-events\"} | json"
    }
   ]
  },
  {
   "title": "Ports Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"ufm-events\", object_type=\"IBPort\"} | json"
    }
   ]
  },
  {
   "title": "Hardware Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{event_type=~\"Hardware\", job=\"ufm-events\"} | json"
    }
   ]
  },
  {
   "title": "Topology Changes Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "{event_type=~\"Fabric_Topology\", job=\"ufm-events\"} | json"
    }
   ]
  }
 ]
}