FROM ubuntu:20.04
ARG _ARCH=x86_64
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
USER root

ENV TZ=Israel
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt clean && \
    apt update && \
    apt upgrade -y && \
    apt install -y python3.8 python3-pip apt-transport-https sqlite3 sudo git 
    #&& \
    #apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
    #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
    #add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    #apt update && \
    #apt install -y docker-ce docker-ce-cli containerd.io

RUN python3 -m pip install mock numba pandas paramiko passlib pexpect pylint requests scp unittest2 bandit blackduck
RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN rm -rf /tmp/*
RUN cat /dev/null > ~/.bash_history
SHELL ["/bin/bash"]
WORKDIR /tmp



