apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ufm-plugin.configMapName" . }}
  namespace: {{ include "ufm-plugin.namespace" . }}
data:
  plugins.yaml: |
    plugins:
{{- if .Values.plugins.items }}
{{- range .Values.plugins.items }}
{{- if and .name .image .tag }}
      - name: {{ .name }}
        host: {{ .host | default (printf "%s-plugin-%s.%s.svc.cluster.local" $.Values.ufmFullname (.name | replace "_" "-") (include "ufm-plugin.namespace" $)) }}
{{- if .port }}
        port: {{ .port }}
{{- end }}
        tag: {{ .tag }}
{{- end }}
{{- end }}
{{- else }}
      []
{{- end }}
