{
 "title": "Infiniband Telemetry",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fabric",
    "query": {
     "query": "label_values(infiniband_port_xmit_wait_ticks, fabric)"
    }
   },
   { "name": "step", "query": "30s" }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "up{}", "legendFormat": "compute" },
    {
     "expr": "up{job=\"ufm-telemetry\"}",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds{}", "legendFormat": "compute" },
    {
     "expr": "scrape_duration_seconds{job=\"ufm-telemetry\"}",
     "legendFormat": "storage"
    }
   ]
  },
  {
   "title": "Number of ports",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (level, peer_level) (PortXmitDataExtended{level!=\"\", peer_level!=\"\"})",
     "legendFormat": "{{level}}->{{peer_level}}"
    }
   ]
  },
  {
   "title": "Average port traffic by level",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "avg by (level, peer_level)(rate(PortXmitDataExtended{level!=\"\", peer_level!=\"\"}[$__rate_interval]) *8)",
     "legendFormat": "{{level}}-to-{{peer_level}}"
    }
   ]
  },
  {
   "title": "Max port traffic by level",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "max by (level, peer_level)(rate(PortXmitDataExtended{level!=\"\", peer_level!=\"\"}[$__rate_interval]) *8)",
     "legendFormat": "{{level}}  - to -{{peer_level}}"
    }
   ]
  },
  {
   "title": "Max congestion",
   "type": "graph",
   "description": "Note: we are currently clamping to 100%, but sometimes it's over 100%.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by (level, peer_level) (Normalized_CBW{level!=\"\", peer_level!=\"\"})",
     "legendFormat": "{{level}}-to-{{peer_level}}"
    }
   ]
  },
  {
   "title": "Writes by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(PortXmitDataExtended{hostname!=\"\", hostname!=\"aggregation\"}[$__rate_interval]) *8",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Reads by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(PortRcvDataExtended{hostname!=\"\", hostname!=\"aggregation\"}[$__rate_interval]) *8",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Transceiver Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "dev_temperature", "legendFormat": "{{node_desc}}" }
   ]
  }
 ]
}