name: PDR Plugin CI Workflow

on:
  push:
     paths:
      - 'plugins/pdr_deterministic_plugin/**'
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: '.:plugins/pdr_deterministic_plugin/ufm_sim_web_service'
      PDRPATH: 'plugins/pdr_deterministic_plugin'

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r $PDRPATH/requirements.txt
        pip install pylint
        pip install pytest-cov

    - name: Run PyLint
      run: pylint --rcfile=$PDRPATH/.pylintrc $PDRPATH/ufm_sim_web_service/

    - name: Run exclusion list class test
      timeout-minutes: 5
      run: pytest -s $PDRPATH/tests/exclude_list_class_tests.py --cov=$PDRPATH

    - name: Test exclusion list REST API
      timeout-minutes: 5
      run: |
        sudo bash $PDRPATH/.pytest/run_pdr_standalone_pytest.sh
        echo "Test exclusion list REST API methods"
        pytest -s $PDRPATH/tests/exclude_list_rest_api_tests.py --cov=$PDRPATH
        sudo bash $PDRPATH/.pytest/terminate_pdr_standalone_pytest.sh

    - name: Run full simulation test
      timeout-minutes: 10
      run: |
        sudo bash $PDRPATH/.pytest/run_pdr_standalone_pytest.sh
        echo "Starting simulated test"
        python $PDRPATH/tests/simulation_telemetry.py
        sudo bash $PDRPATH/.pytest/terminate_pdr_standalone_pytest.sh
