name: PDR Plugin CI Workflow

on:
  push:
     paths:
      - 'plugins/pdr_deterministic_plugin/**'
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: '.:plugins/pdr_deterministic_plugin/ufm_sim_web_service'

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r plugins/pdr_deterministic_plugin/requirements.txt
        pip install pylint
        pip install pytest pytest-cov
    
    - name: Run PyLint
      run: pylint --rcfile=plugins/pdr_deterministic_plugin/.pylintrc plugins/pdr_deterministic_plugin

    - name: Run exclusion list class test
      run: pytest -s plugins/pdr_deterministic_plugin/tests/exclude_list_class_tests.py --cov=plugins/pdr_deterministic_plugin/tests/exclude_list_class_tests.py

    - name: Test exclusion list REST API
      run: |
        sudo bash plugins/pdr_deterministic_plugin/.pytest/run_pdr_standalone_pytest.sh
        echo "Test exclusion list REST API methods"
        sleep 10
        pytest -s plugins/pdr_deterministic_plugin/tests/exclude_list_rest_api_tests.py --cov=plugins/pdr_deterministic_plugin/ufm_sim_web_service/api/pdr_plugin_api.py
        echo "Terminating standalone PDR process"
        pkill -9 -f isolation_algo.py 2>/dev/null || true

    - name: Run full simulation test
      run: |
        sudo bash plugins/pdr_deterministic_plugin/.pytest/run_pdr_standalone_pytest.sh
        echo "Starting simulated test"
        python plugins/pdr_deterministic_plugin/tests/simulation_telemetry.py
        echo "Terminating standalone PDR process"
        pkill -9 -f isolation_algo.py 2>/dev/null || true
