name: PDR Plugin CI Workflow

on:
  push:
     paths:
      - 'plugins/pdr_deterministic_plugin/**'
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r plugins/pdr_deterministic_plugin/requirements.txt
        pip install pylint
        pip install pytest pytest-cov
    
    - name: Run PyLint
      run: pylint --rcfile=plugins/pdr_deterministic_plugin/.pylintrc plugins/pdr_deterministic_plugin
    
    - name: Test exclude list with pytest
      run: pytest plugins/pdr_deterministic_plugin/tests/exclude_list_tests.py --doctest-modules --junitxml=junit/exclude_list_tests_results.xml --cov=com --cov-report=xml --cov-report=html