name: PDR Plugin CI Workflow

on:
  push:
     paths:
      - 'plugins/pdr_deterministic_plugin/**'
jobs:
  ufm-pdr-deterministic-plugin:
    runs-on: ubuntu-latest
    
    env:
      plugin_dir: pdr_deterministic_plugin
      plugin_name: ufm-plugin-pdr_deterministic
      DOCKER_CLI_EXPERIMENTAL: enabled
    
    steps:
      - name: Build Plugin
        run: |
          cd plugins/$plugin_dir/build
          bash -x ./docker_build.sh latest /
          ls -l /
          cp /ufm-plugin* /auto/UFM/tmp/${JOB_NAME}/${BUILD_ID}/
    
      - name: remove plugin if exists on the location
        run: |
          env
          bash -x plugins/pdr_deterministic_plugin/.ci/do_remove_plugin.sh
        
      - name: Install the new plugin on Server
        run: |
          env
          pwd
          export PASSWORD=$PASSWORD
          bash -x plugins/pdr_deterministic_plugin/.ci/do_install_plugin_server.sh
          
      - name: load plugin
        run: |
          bash -x plugins/pdr_deterministic_plugin/.ci/do_load_plugin.sh
    
      - name: add plugin
        run: |
          bash -x plugins/pdr_deterministic_plugin/.ci/do_add_plugin.sh 
      
      - name: remove plugin end
        run: |
          bash -x plugins/pdr_deterministic_plugin/.ci/do_remove_plugin.sh

  build:
    runs-on: ubuntu-latest
  
    env:
      PYTHONPATH: '.:plugins/pdr_deterministic_plugin/ufm_sim_web_service'

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r plugins/pdr_deterministic_plugin/requirements.txt
        pip install pylint
        pip install pytest pytest-cov
    
    - name: Run PyLint
      run: pylint --rcfile=plugins/pdr_deterministic_plugin/.pylintrc plugins/pdr_deterministic_plugin
    
    - name: Test exclude list with pytest
      run: pytest plugins/pdr_deterministic_plugin/tests/exclude_list_tests.py --doctest-modules --junitxml=junit/exclude_list_tests_results.xml --cov=com --cov-report=xml --cov-report=html
