name: TFS Plugin CI Workflow

on:
  push:
     paths:
      - 'plugins/fluentd_telemetry_plugin/**'
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r plugins/fluentd_telemetry_plugin/requirements.txt
        pip install pylint
    - name: Run PyLint
      run: pylint --rcfile=plugins/fluentd_telemetry_plugin/.pylintrc plugins/fluentd_telemetry_plugin

    - name: Run pytests
      run: |
        pytest plugins/fluentd_telemetry_plugin/tests
