name: Ufm log analyzer CI Workflow

on: 
  push:
    paths:
      - 'plugins/ufm_log_analyzer_plugin/**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      SCRIPT_DIR: "plugins/ufm_log_analyzer_plugin"
      PYTHONPATH: "${{ env.SCRIPT_DIR }}/src:${{ env.SCRIPT_DIR }}/../../"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install dependencies and run PyLint
      run: |
        cd ${{ env.SCRIPT_DIR }}
        pip install -r src/loganalyze/requirements.txt
        pip install pylint
        pylint --rcfile=src/loganalyze/.pylintrc src/loganalyze
